#####################################################
#
#	Log Preference
#
#
#
# 																		 2024.04.19
# 																		 Seunggwan.Back
#
#####################################################

#####################################################
path: ./logs
debug: true
level: 99
rotacnt: 5
rotafreq: 86400