#####################################################
#
#	Sample Preference
#
#
#
#
#####################################################

#####################################################
#Section: server
server:
  host: 0.0.0.0:8080
  debug: true